name: ai-climate-prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - tensorflow
  - keras
  - pytorch
  - scipy
  - scikit-image
  - xgboost
  - lightgbm
  - geopandas
  - requests
  - tqdm
  - pip:
      - plotly
      - jupyterlab
      - statsmodels
      - mlflow
  - pip:
      - flask
      - gunicorn
  - pip:
      - pyjwt
      - docker
  - pytest
  - black
  - flake8
  - pre-commit
  - pylint
  - jupyterlab-git
  - spyder
